### ISSUE TITLE
RestClient::Forbidden: 403 Forbidden

### ISSUE THREAD

**Issue by ipatovanton** [Timrael/social_shares#19]
I gets this errorRestClient::Forbidden: 403 Forbidden
	from /Users/ipatov/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.1/lib/restclient/abstract_response.rb:223:in `exception_with_response'
	from /Users/ipatov/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.1/lib/restclient/abstract_response.rb:103:in `return!'
	from /Users/ipatov/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.1/lib/restclient/request.rb:809:in `process_result'
	from /Users/ipatov/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.1/lib/restclient/request.rb:725:in `block in transmit'
	from /Users/ipatov/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /Users/ipatov/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.1/lib/restclient/request.rb:715:in `transmit'
	from /Users/ipatov/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.1/lib/restclient/request.rb:145:in `execute'
	from /Users/ipatov/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.1/lib/restclient/request.rb:52:in `execute'
	from /Users/ipatov/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.1/lib/restclient/resource.rb:51:in `get'
	from /Users/ipatov/.rvm/gems/ruby-2.3.0/gems/social_shares-0.3.2/lib/social_shares/base.rb:48:in `get'
	from /Users/ipatov/.rvm/gems/ruby-2.3.0/gems/social_shares-0.3.2/lib/social_shares/facebook.rb:6:in `shares!'
	from /Users/ipatov/.rvm/gems/ruby-2.3.0/gems/social_shares-0.3.2/lib/social_shares.rb:54:in `block (2 levels) in singleton class'
	from /Users/ipatov/.rvm/gems/ruby-2.3.0/gems/social_shares-0.3.2/lib/social_shares.rb:119:in `block (2 levels) in selected_base'
	from /Users/ipatov/.rvm/gems/ruby-2.3.0/gems/social_shares-0.3.2/lib/social_shares.rb:113:in `block (2 levels) in thread_pool'

**Comment by joenas** [comment]
Thats probably because you're getting [rate limited](https://stackoverflow.com/a/8805436)
